//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	externalRef0 "github.com/dharmab/hyperboard/pkg/types"
	"github.com/oapi-codegen/runtime"
)

// Cursor defines model for Cursor.
type Cursor = string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Limit defines model for Limit.
type Limit = int

// Search defines model for Search.
type Search = string

// Force defines model for force.
type Force = bool

// Id defines model for id.
type Id = externalRef0.ID

// Tag defines model for tag.
type Tag = externalRef0.TagName

// TagCategory defines model for tagCategory.
type TagCategory = externalRef0.TagCategoryName

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse = Error

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse = Error

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse = Error

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse = Error

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse = Error

// NoteResponse defines model for NoteResponse.
type NoteResponse = externalRef0.Note

// NotesResponse defines model for NotesResponse.
type NotesResponse struct {
	Cursor *Cursor              `json:"cursor,omitempty"`
	Items  *[]externalRef0.Note `json:"items,omitempty"`
}

// PostResponse defines model for PostResponse.
type PostResponse = externalRef0.Post

// PostsResponse defines model for PostsResponse.
type PostsResponse struct {
	Cursor *Cursor              `json:"cursor,omitempty"`
	Items  *[]externalRef0.Post `json:"items,omitempty"`
}

// TagCategoriesResponse defines model for TagCategoriesResponse.
type TagCategoriesResponse struct {
	Cursor *Cursor                     `json:"cursor,omitempty"`
	Items  *[]externalRef0.TagCategory `json:"items,omitempty"`
}

// TagCategoryResponse defines model for TagCategoryResponse.
type TagCategoryResponse = externalRef0.TagCategory

// TagResponse defines model for TagResponse.
type TagResponse = externalRef0.Tag

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Cursor *Cursor             `json:"cursor,omitempty"`
	Items  *[]externalRef0.Tag `json:"items,omitempty"`
}

// TooManyRequestsResponse defines model for TooManyRequestsResponse.
type TooManyRequestsResponse = Error

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = Error

// UploadPostResponse defines model for UploadPostResponse.
type UploadPostResponse = externalRef0.Post

// NoteRequest defines model for NoteRequest.
type NoteRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// PostRequest defines model for PostRequest.
type PostRequest = externalRef0.Post

// TagCategoryRequest defines model for TagCategoryRequest.
type TagCategoryRequest = externalRef0.TagCategory

// TagRequest defines model for TagRequest.
type TagRequest = externalRef0.Tag

// CreateNoteJSONBody defines parameters for CreateNote.
type CreateNoteJSONBody struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// PutNoteJSONBody defines parameters for PutNote.
type PutNoteJSONBody struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// GetSimilarPostsParams defines parameters for GetSimilarPosts.
type GetSimilarPostsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTagCategoriesParams defines parameters for GetTagCategories.
type GetTagCategoriesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTagsParams defines parameters for GetTags.
type GetTagsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ConvertTagToAliasJSONBody defines parameters for ConvertTagToAlias.
type ConvertTagToAliasJSONBody struct {
	Target string `json:"target"`
}

// UploadPostParams defines parameters for UploadPost.
type UploadPostParams struct {
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody CreateNoteJSONBody

// PutNoteJSONRequestBody defines body for PutNote for application/json ContentType.
type PutNoteJSONRequestBody PutNoteJSONBody

// PutPostJSONRequestBody defines body for PutPost for application/json ContentType.
type PutPostJSONRequestBody = externalRef0.Post

// PutTagCategoryJSONRequestBody defines body for PutTagCategory for application/json ContentType.
type PutTagCategoryJSONRequestBody = externalRef0.TagCategory

// PutTagJSONRequestBody defines body for PutTag for application/json ContentType.
type PutTagJSONRequestBody = externalRef0.Tag

// ConvertTagToAliasJSONRequestBody defines body for ConvertTagToAlias for application/json ContentType.
type ConvertTagToAliasJSONRequestBody ConvertTagToAliasJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all notes.
	// (GET /api/v1/notes)
	GetNotes(w http.ResponseWriter, r *http.Request)
	// Create a note.
	// (POST /api/v1/notes)
	CreateNote(w http.ResponseWriter, r *http.Request)
	// Delete a note by ID.
	// (DELETE /api/v1/notes/{id})
	DeleteNote(w http.ResponseWriter, r *http.Request, id externalRef0.ID)
	// Get a note by ID.
	// (GET /api/v1/notes/{id})
	GetNote(w http.ResponseWriter, r *http.Request, id externalRef0.ID)
	// Update a note by ID.
	// (PUT /api/v1/notes/{id})
	PutNote(w http.ResponseWriter, r *http.Request, id externalRef0.ID)
	// Search for posts.
	// (GET /api/v1/posts)
	GetPosts(w http.ResponseWriter, r *http.Request, params GetPostsParams)
	// Delete a post's metadata and content.
	// (DELETE /api/v1/posts/{id})
	DeletePost(w http.ResponseWriter, r *http.Request, id Id)
	// Get a post's metadata by ID.
	// (GET /api/v1/posts/{id})
	GetPost(w http.ResponseWriter, r *http.Request, id Id)
	// Replace a post's metadata. This does not create a new post - use uploadPost to create a new post.
	// (PUT /api/v1/posts/{id})
	PutPost(w http.ResponseWriter, r *http.Request, id Id)
	// Replace a post's content file. The server re-processes the file and updates contentUrl and mimeType.
	// (PUT /api/v1/posts/{id}/content)
	ReplacePostContent(w http.ResponseWriter, r *http.Request, id Id)
	// Get posts that are visually similar to the given post based on perceptual hash.
	// (GET /api/v1/posts/{id}/similar)
	GetSimilarPosts(w http.ResponseWriter, r *http.Request, id Id, params GetSimilarPostsParams)
	// Replace a post's thumbnail image. The server processes the image into a WebP thumbnail.
	// (PUT /api/v1/posts/{id}/thumbnail)
	ReplacePostThumbnail(w http.ResponseWriter, r *http.Request, id Id)
	// List tag categories.
	// (GET /api/v1/tagCategories)
	GetTagCategories(w http.ResponseWriter, r *http.Request, params GetTagCategoriesParams)
	// Delete a tag category. All tags with this category will have their category unset.
	// (DELETE /api/v1/tagCategories/{tagCategory})
	DeleteTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// Get a tag category by name.
	// (GET /api/v1/tagCategories/{tagCategory})
	GetTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// Create or replace a tag category by name.
	// (PUT /api/v1/tagCategories/{tagCategory})
	PutTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// List tags.
	// (GET /api/v1/tags)
	GetTags(w http.ResponseWriter, r *http.Request, params GetTagsParams)
	// Delete a tag. The tag will be removed from any posts and tag categories.
	// (DELETE /api/v1/tags/{tag})
	DeleteTag(w http.ResponseWriter, r *http.Request, tag Tag)
	// Get a tag by name.
	// (GET /api/v1/tags/{tag})
	GetTag(w http.ResponseWriter, r *http.Request, tag Tag)
	// Create or replace a tag by name.
	// (PUT /api/v1/tags/{tag})
	PutTag(w http.ResponseWriter, r *http.Request, tag Tag)
	// Convert a tag to an alias of another tag. Re-tags all posts and merges aliases atomically.
	// (POST /api/v1/tags/{tag}/convert-to-alias)
	ConvertTagToAlias(w http.ResponseWriter, r *http.Request, tag Tag)
	// Upload a new post's content.
	// (POST /api/v1/upload)
	UploadPost(w http.ResponseWriter, r *http.Request, params UploadPostParams)

	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetNotes operation middleware
func (siw *ServerInterfaceWrapper) GetNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id externalRef0.ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id externalRef0.ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutNote operation middleware
func (siw *ServerInterfaceWrapper) PutNote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id externalRef0.ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutNote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPosts operation middleware
func (siw *ServerInterfaceWrapper) GetPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPost operation middleware
func (siw *ServerInterfaceWrapper) PutPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplacePostContent operation middleware
func (siw *ServerInterfaceWrapper) ReplacePostContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplacePostContent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSimilarPosts operation middleware
func (siw *ServerInterfaceWrapper) GetSimilarPosts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSimilarPostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSimilarPosts(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplacePostThumbnail operation middleware
func (siw *ServerInterfaceWrapper) ReplacePostThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplacePostThumbnail(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagCategories operation middleware
func (siw *ServerInterfaceWrapper) GetTagCategories(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagCategoriesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagCategories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTagCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagCategory operation middleware
func (siw *ServerInterfaceWrapper) GetTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTagCategory operation middleware
func (siw *ServerInterfaceWrapper) PutTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTags operation middleware
func (siw *ServerInterfaceWrapper) GetTags(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTag operation middleware
func (siw *ServerInterfaceWrapper) GetTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTag operation middleware
func (siw *ServerInterfaceWrapper) PutTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConvertTagToAlias operation middleware
func (siw *ServerInterfaceWrapper) ConvertTagToAlias(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConvertTagToAlias(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadPost operation middleware
func (siw *ServerInterfaceWrapper) UploadPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadPostParams

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", r.URL.Query(), &params.Force)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "force", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPost(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/notes", wrapper.GetNotes)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/notes", wrapper.CreateNote)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/notes/{id}", wrapper.DeleteNote)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/notes/{id}", wrapper.GetNote)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/notes/{id}", wrapper.PutNote)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/posts", wrapper.GetPosts)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/posts/{id}", wrapper.DeletePost)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/posts/{id}", wrapper.GetPost)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/posts/{id}", wrapper.PutPost)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/posts/{id}/content", wrapper.ReplacePostContent)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/posts/{id}/similar", wrapper.GetSimilarPosts)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/posts/{id}/thumbnail", wrapper.ReplacePostThumbnail)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tagCategories", wrapper.GetTagCategories)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.DeleteTagCategory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.GetTagCategory)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.PutTagCategory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tags", wrapper.GetTags)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.DeleteTag)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.GetTag)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.PutTag)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/tags/{tag}/convert-to-alias", wrapper.ConvertTagToAlias)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/upload", wrapper.UploadPost)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadiness)

	return m
}
