// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	externalRef0 "github.com/dharmab/hyperboard/pkg/types"
)

// Cursor defines model for Cursor.
type Cursor = string

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Limit defines model for Limit.
type Limit = int

// Search defines model for Search.
type Search = string

// Id defines model for id.
type Id = externalRef0.ID

// Tag defines model for tag.
type Tag = externalRef0.TagName

// TagCategory defines model for tagCategory.
type TagCategory = externalRef0.TagCategoryName

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse = Error

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse = Error

// ImageResponse defines model for ImageResponse.
type ImageResponse = externalRef0.Image

// ImagesResponse defines model for ImagesResponse.
type ImagesResponse struct {
	Cursor *Cursor               `json:"cursor,omitempty"`
	Items  *[]externalRef0.Image `json:"items,omitempty"`
}

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse = Error

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse = Error

// TagCategoriesResponse defines model for TagCategoriesResponse.
type TagCategoriesResponse struct {
	Cursor *Cursor                     `json:"cursor,omitempty"`
	Items  *[]externalRef0.TagCategory `json:"items,omitempty"`
}

// TagCategoryResponse defines model for TagCategoryResponse.
type TagCategoryResponse = externalRef0.TagCategory

// TagResponse defines model for TagResponse.
type TagResponse = externalRef0.Tag

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Cursor *Cursor             `json:"cursor,omitempty"`
	Items  *[]externalRef0.Tag `json:"items,omitempty"`
}

// TooManyRequestsResponse defines model for TooManyRequestsResponse.
type TooManyRequestsResponse = Error

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = Error

// ImageRequest defines model for ImageRequest.
type ImageRequest = externalRef0.Image

// TagCategoryRequest defines model for TagCategoryRequest.
type TagCategoryRequest = externalRef0.TagCategory

// TagRequest defines model for TagRequest.
type TagRequest = externalRef0.Tag

// GetImagesParams defines parameters for GetImages.
type GetImagesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// GetTagCategoriesParams defines parameters for GetTagCategories.
type GetTagCategoriesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTagsParams defines parameters for GetTags.
type GetTagsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutImageJSONRequestBody defines body for PutImage for application/json ContentType.
type PutImageJSONRequestBody = externalRef0.Image

// PutTagCategoryJSONRequestBody defines body for PutTagCategory for application/json ContentType.
type PutTagCategoryJSONRequestBody = externalRef0.TagCategory

// PutTagJSONRequestBody defines body for PutTag for application/json ContentType.
type PutTagJSONRequestBody = externalRef0.Tag
