//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	externalRef0 "github.com/dharmab/hyperboard/pkg/types"
	"github.com/oapi-codegen/runtime"
)

// Cursor defines model for Cursor.
type Cursor = string

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Limit defines model for Limit.
type Limit = int

// Search defines model for Search.
type Search = string

// Id defines model for id.
type Id = externalRef0.ID

// Tag defines model for tag.
type Tag = externalRef0.TagName

// TagCategory defines model for tagCategory.
type TagCategory = externalRef0.TagCategoryName

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse = Error

// ForbiddenResponse defines model for ForbiddenResponse.
type ForbiddenResponse = Error

// ImageResponse defines model for ImageResponse.
type ImageResponse = externalRef0.Image

// ImagesResponse defines model for ImagesResponse.
type ImagesResponse struct {
	Cursor *Cursor               `json:"cursor,omitempty"`
	Items  *[]externalRef0.Image `json:"items,omitempty"`
}

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse = Error

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse = Error

// TagCategoriesResponse defines model for TagCategoriesResponse.
type TagCategoriesResponse struct {
	Cursor *Cursor                     `json:"cursor,omitempty"`
	Items  *[]externalRef0.TagCategory `json:"items,omitempty"`
}

// TagCategoryResponse defines model for TagCategoryResponse.
type TagCategoryResponse = externalRef0.TagCategory

// TagResponse defines model for TagResponse.
type TagResponse = externalRef0.Tag

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Cursor *Cursor             `json:"cursor,omitempty"`
	Items  *[]externalRef0.Tag `json:"items,omitempty"`
}

// TooManyRequestsResponse defines model for TooManyRequestsResponse.
type TooManyRequestsResponse = Error

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = Error

// ImageRequest defines model for ImageRequest.
type ImageRequest = externalRef0.Image

// TagCategoryRequest defines model for TagCategoryRequest.
type TagCategoryRequest = externalRef0.TagCategory

// TagRequest defines model for TagRequest.
type TagRequest = externalRef0.Tag

// GetImagesParams defines parameters for GetImages.
type GetImagesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`
}

// GetTagCategoriesParams defines parameters for GetTagCategories.
type GetTagCategoriesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTagsParams defines parameters for GetTags.
type GetTagsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutImageJSONRequestBody defines body for PutImage for application/json ContentType.
type PutImageJSONRequestBody = externalRef0.Image

// PutTagCategoryJSONRequestBody defines body for PutTagCategory for application/json ContentType.
type PutTagCategoryJSONRequestBody = externalRef0.TagCategory

// PutTagJSONRequestBody defines body for PutTag for application/json ContentType.
type PutTagJSONRequestBody = externalRef0.Tag

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search for images.
	// (GET /api/v1/images)
	GetImages(w http.ResponseWriter, r *http.Request, params GetImagesParams)
	// Delete an image's metadata and content.
	// (DELETE /api/v1/images/{id})
	DeleteImage(w http.ResponseWriter, r *http.Request, id Id)
	// Get an image's metadata by ID.
	// (GET /api/v1/images/{id})
	GetImage(w http.ResponseWriter, r *http.Request, id Id)
	// Replace an image's metadata. This does not create a new image - use uploadImage to create a new image.
	// (PUT /api/v1/images/{id})
	PutImage(w http.ResponseWriter, r *http.Request, id Id)
	// List tag categories.
	// (GET /api/v1/tagCategories)
	GetTagCategories(w http.ResponseWriter, r *http.Request, params GetTagCategoriesParams)
	// Delete a tag category. All tags with this category will have their category unset.
	// (DELETE /api/v1/tagCategories/{tagCategory})
	DeleteTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// Get a tag category by name.
	// (GET /api/v1/tagCategories/{tagCategory})
	GetTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// Create or replace a tag category by name.
	// (PUT /api/v1/tagCategories/{tagCategory})
	PutTagCategory(w http.ResponseWriter, r *http.Request, tagCategory TagCategory)
	// List tags.
	// (GET /api/v1/tags)
	GetTags(w http.ResponseWriter, r *http.Request, params GetTagsParams)
	// Delete a tag. The tag will be removed from any images and tag categories.
	// (DELETE /api/v1/tags/{tag})
	DeleteTag(w http.ResponseWriter, r *http.Request, tag Tag)
	// Get a tag by name.
	// (GET /api/v1/tags/{tag})
	GetTag(w http.ResponseWriter, r *http.Request, tag Tag)
	// Create or replace a tag by name.
	// (PUT /api/v1/tags/{tag})
	PutTag(w http.ResponseWriter, r *http.Request, tag Tag)

	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetImages operation middleware
func (siw *ServerInterfaceWrapper) GetImages(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetImagesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteImage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutImage operation middleware
func (siw *ServerInterfaceWrapper) PutImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutImage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagCategories operation middleware
func (siw *ServerInterfaceWrapper) GetTagCategories(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagCategoriesParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagCategories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTagCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagCategory operation middleware
func (siw *ServerInterfaceWrapper) GetTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTagCategory operation middleware
func (siw *ServerInterfaceWrapper) PutTagCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tagCategory" -------------
	var tagCategory TagCategory

	err = runtime.BindStyledParameterWithOptions("simple", "tagCategory", r.PathValue("tagCategory"), &tagCategory, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tagCategory", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTagCategory(w, r, tagCategory)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTags operation middleware
func (siw *ServerInterfaceWrapper) GetTags(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTag operation middleware
func (siw *ServerInterfaceWrapper) GetTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTag operation middleware
func (siw *ServerInterfaceWrapper) PutTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag Tag

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTag(w, r, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/images", wrapper.GetImages)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/images/{id}", wrapper.DeleteImage)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/images/{id}", wrapper.GetImage)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/images/{id}", wrapper.PutImage)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tagCategories", wrapper.GetTagCategories)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.DeleteTagCategory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.GetTagCategory)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/tagCategories/{tagCategory}", wrapper.PutTagCategory)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tags", wrapper.GetTags)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.DeleteTag)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.GetTag)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/tags/{tag}", wrapper.PutTag)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReadiness)

	return m
}
