#yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/tags/v2.4.1/configuration-schema.json
package: api
import-mapping:
  types-spec.yaml: github.com/dharmab/hyperboard/internal/types
generate:
  models: true
  std-http-server: true
output: gen.go