openapi: "3.0.0"
info:
  title: Hyperboard Types
  version: 0.1.0
paths: {}
components:
  schemas:
    ID:
      type: string
      format: uuid
      x-go-name: ID
    TagName:
      type: string
    TagCategoryName:
      type: string
    URL:
      type: string
    Description:
      type: string
    Timestamp:
      type: string
      format: date-time
    Tag:
      type: object
      required:
        - name
        - description
        - createdAt
        - updatedAt
      properties:
        name:
          $ref: "#/components/schemas/TagName"
        category:
          $ref: "#/components/schemas/TagCategoryName"
        description:
          type: string
        aliases:
          type: array
          items:
            type: string
        postCount:
          type: integer
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        updatedAt:
          $ref: "#/components/schemas/Timestamp"
    TagCategory:
      type: object
      required:
        - name
        - description
        - color
        - createdAt
        - updatedAt
      properties:
        name:
          $ref: "#/components/schemas/TagCategoryName"
        description:
          $ref: "#/components/schemas/Description"
        color:
          type: string
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        updatedAt:
          $ref: "#/components/schemas/Timestamp"
    Post:
      type: object
      required:
        - id
        - mimeType
        - contentUrl
        - thumbnailUrl
        - note
        - hasAudio
        - tags
        - createdAt
        - updatedAt
      properties:
        id:
          $ref: "#/components/schemas/ID"
        mimeType:
          type: string
        contentUrl:
          $ref: "#/components/schemas/URL"
        thumbnailUrl:
          $ref: "#/components/schemas/URL"
        note:
          type: string
        hasAudio:
          type: boolean
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagName"
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        updatedAt:
          $ref: "#/components/schemas/Timestamp"
    Note:
      type: object
      required:
        - id
        - title
        - content
        - createdAt
        - updatedAt
      properties:
        id:
          $ref: "#/components/schemas/ID"
        title:
          type: string
        content:
          type: string
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        updatedAt:
          $ref: "#/components/schemas/Timestamp"
