openapi: "3.0.0"
info:
  title: Hyperboard Types
  version: 0.1.0
paths: {}
components:
  schemas:
    ID:
      type: string
      format: uuid
      x-go-name: ID
    TagName:
      type: string
    TagCategoryName:
      type: string
    URL:
      type: string
    Description:
      type: string
    Timestamp:
      type: string
      format: date-time
    Tag:
      type: object
      required:
        - name
        - description
        - createdAt
        - updatedAt
      properties:
        name:
          $ref: "#/components/schemas/TagName"
        category:
          $ref: "#/components/schemas/TagCategoryName"
        description:
          type: string
          x-go-type-skip-optional-pointer: true
        aliases:
          type: array
          items:
            type: string
        cascadingTags:
          type: array
          items:
            $ref: "#/components/schemas/TagName"
        postCount:
          type: integer
          readOnly: true
        createdAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
        updatedAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
    TagCategory:
      type: object
      required:
        - name
        - description
        - color
        - createdAt
        - updatedAt
      properties:
        name:
          $ref: "#/components/schemas/TagCategoryName"
        description:
          allOf:
            - $ref: "#/components/schemas/Description"
          x-go-type-skip-optional-pointer: true
        color:
          type: string
          description: Hex color.
          pattern: '^#[0-9A-Fa-f]{6}$'
          default: "#888888"
          example: "#ff0000"
          x-go-type-skip-optional-pointer: true
        tagCount:
          type: integer
          readOnly: true
        createdAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
        updatedAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
    Post:
      type: object
      required:
        - id
        - mimeType
        - contentUrl
        - thumbnailUrl
        - note
        - hasAudio
        - tags
        - createdAt
        - updatedAt
      properties:
        id:
          $ref: "#/components/schemas/ID"
        mimeType:
          type: string
          readOnly: true
        contentUrl:
          allOf:
            - $ref: "#/components/schemas/URL"
          readOnly: true
        thumbnailUrl:
          allOf:
            - $ref: "#/components/schemas/URL"
          readOnly: true
        note:
          type: string
          x-go-type-skip-optional-pointer: true
        hasAudio:
          type: boolean
          readOnly: true
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagName"
          x-go-type-skip-optional-pointer: true
        tagColors:
          type: object
          additionalProperties:
            type: string
          readOnly: true
        cascadingTags:
          type: array
          items:
            $ref: "#/components/schemas/TagName"
          readOnly: true
        createdAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
        updatedAt:
          allOf:
            - $ref: "#/components/schemas/Timestamp"
          readOnly: true
    Note:
      type: object
      required:
        - id
        - title
        - content
        - createdAt
        - updatedAt
      properties:
        id:
          $ref: "#/components/schemas/ID"
        title:
          type: string
        content:
          type: string
        createdAt:
          $ref: "#/components/schemas/Timestamp"
        updatedAt:
          $ref: "#/components/schemas/Timestamp"
