apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperboard-api
  labels:
    app.kubernetes.io/name: hyperboard-api
    app.kubernetes.io/part-of: hyperboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hyperboard-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hyperboard-api
        app.kubernetes.io/part-of: hyperboard
    spec:
      enableServiceLinks: false
      containers:
        - name: hyperboard-api
          image: hyperboard-api
          args:
            - --postgresql-host=postgresql
            - --postgresql-user=postgres
            - --postgresql-database=postgres
            - --postgresql-ssl-mode=disable
            - --postgresql-password=postgres
            - --admin-password=hyperboard
          ports:
            - name: api
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: api
          readinessProbe:
            httpGet:
              path: /readyz
              port: api
---
apiVersion: v1
kind: Service
metadata:
  name: hyperboard-api
  labels:
    app.kubernetes.io/name: hyperboard-api
    app.kubernetes.io/part-of: hyperboard
spec:
  selector:
    app.kubernetes.io/name: hyperboard-api
  ports:
    - port: 80
      targetPort: api
  type: ClusterIP
