apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperboard-web
  labels:
    app.kubernetes.io/name: hyperboard-web
    app.kubernetes.io/part-of: hyperboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hyperboard-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hyperboard-web
        app.kubernetes.io/part-of: hyperboard
    spec:
      enableServiceLinks: false
      containers:
        - name: hyperboard-web
          image: hyperboard-web
          args:
            - --admin-password=hyperboard
            - --api-url=http://hyperboard-api
            - --log-level=debug
            - --tag-filters=[{"label":"Rating","tags":["rating:safe","rating:questionable","rating:explicit"]},{"label":"No AI","tags":["-ai_generated"]}]
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hyperboard-web
  labels:
    app.kubernetes.io/name: hyperboard-web
    app.kubernetes.io/part-of: hyperboard
spec:
  selector:
    app.kubernetes.io/name: hyperboard-web
  ports:
    - port: 80
      targetPort: http
  type: ClusterIP
