// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Description defines model for Description.
type Description = string

// ID defines model for ID.
type ID = openapi_types.UUID

// Image defines model for Image.
type Image struct {
	ContentRef   URL       `json:"contentRef"`
	CreatedAt    Timestamp `json:"createdAt"`
	ID           ID        `json:"id"`
	MimeType     string    `json:"mimeType"`
	Tags         []TagName `json:"tags"`
	ThumbnailRef URL       `json:"thumbnailRef"`
	UpdatedAt    Timestamp `json:"updatedAt"`
}

// Tag defines model for Tag.
type Tag struct {
	CreatedAt   Timestamp `json:"createdAt"`
	Description string    `json:"description"`
	ID          ID        `json:"id"`
	Name        TagName   `json:"name"`
	UpdatedAt   Timestamp `json:"updatedAt"`
}

// TagCategory defines model for TagCategory.
type TagCategory struct {
	CreatedAt   Timestamp       `json:"createdAt"`
	Description Description     `json:"description"`
	ID          ID              `json:"id"`
	Name        TagCategoryName `json:"name"`
	UpdatedAt   Timestamp       `json:"updatedAt"`
}

// TagCategoryName defines model for TagCategoryName.
type TagCategoryName = string

// TagName defines model for TagName.
type TagName = string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// URL defines model for URL.
type URL = string
