CREATE TABLE IF NOT EXISTS images (
    id SERIAL PRIMARY KEY,
    mime_type TEXT NOT NULL,
    content_url TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
